### ISSUE TITLE
Link JSON http://sample-music.herokuapp.com/  not work

### ISSUE THREAD

**Issue by fanfantasi** [singhbhavneet/Bungee#3]
Link http://sample-music.herokuapp.com not working

**Comment by developerpaaji** [comment]
I know working on it

**Comment by developerpaaji** [comment]
http://funkmusic.herokuapp.com new url. Please dont try to misuse it

**Comment by fanfantasi** [comment]
Thank you very much, i try it

Pada tanggal Jum, 22 Mar 2019 18.30, Bhavneet Singh <
notifications@github.com> menulis:
