### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [singhbhavneet/Bungee#4]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by developerpaaji** [comment]
Thanku I dont have any problem.Thanku for appreciation

**Comment by mansya** [comment]
I see this logo too familiar. Are you not interested if I submit a logo that is unique and might interest you?

**Comment by developerpaaji** [comment]
Ok no problem

**Comment by mansya** [comment]
Hi sir. I have completed the design for this project. do you like it ? if yes please tell me which one you like. and if there are changes please let me know
![Bungee](https://user-images.githubusercontent.com/33461607/58752868-482d9b80-84e0-11e9-9886-20840db0ff1b.png)
This combination of letters B and music icons. the reason for using the letter B is because the first letter of the word bungee is B. so I combine them so that this icon matches the name of the project

**Comment by developerpaaji** [comment]
2nd one is good

**Comment by mansya** [comment]
Hi sir. I have done all this. and also uploaded all the files to this [**Drive**](https://drive.google.com/open?id=1H16G0b5F4_As_YlNsMY0_Gpe6Z8o3QdD). and I have also sent you [**PULL REQUESTS**](https://github.com/singhbhavneet/Bungee/pull/5). please check
